version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=akash1234
      - POSTGRES_USER=akash
      - POSTGRES_DB=myapp
    restart: always