version: '3.1'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=akash1234
      - POSTGRES_USER=akash
      - POSTGRES_DB=myapp
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    volumes:
      - ./rdata:/rdata
      - ./docker_datas/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: akash1234
      REDIS_PORT: 6379
      REDIS_DATABASES: 1

  # kafka:
  #   image: confluentinc/cp-kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_ZOOKEEPER_CONNECT=192.168.31.212:2181
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.31.212:9092
  #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  app:
    image: akashmondal0/sky-media:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      # MONGO_URI: mongodb://root:akash1234@192.168.31.212:27017/chatapp?authSource=admin
      # REDIS_URI: redis://:akash1234@192.168.31.212:6379
      # JWT_SECRET: dRYjpuVfGUTCDttLnTON6KBP6q1kDLUD9ocnoVZAx7Ggmr0aMWK0ABw8JbMys+QSChO0rk+Csso2blKRqZSzlmOnA1tfgQUKybSIJTavNuJF4BEiUXhP/iXa2srdKY+8PdrgRVLPnfFy/yTUY9VzfIBBQH2wNpqvSSWy5/E9zporn4kVkXIQmXm+JPF+pd6UNcRg89AQebZbc1b32hOkxPpwTAMcfYLQAOH5SfcjpcH0nBCPPqhLFxXwoRd5+PHufwwkPUKHu9STcAL4lJW1uosg8XNX5GjPLXpdSu55UWtcTWIVyAdb0FHzxoVMvcwZfZzhihwrpXiJMrorXwew2g==
  
  # prom-server:
  #   image: prom/prometheus
  #   restart: always
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  # grafana:
  #   image: grafana/grafana-oss:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"

  # grafana-loki:
  #   image: grafana/loki:latest
  #   restart: always
  #   ports:
  #     - "3100:3100"